task: detection

num_classes: 2
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ee22s501/cvip/data_detect_coco/train/
    ann_file: /home/ee22s501/cvip/data_detect_coco/annotations/instances_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 32
  num_workers: 8
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ee22s501/cvip/data_detect_coco/val/
    ann_file: /home/ee22s501/cvip/data_detect_coco/annotations/instances_val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 32
  num_workers: 8
  drop_last: False
